FROM amazonlinux:2016.09

MAINTAINER "Sergey Zolotorev" <sergey.zolotorev@dsr-company.com>

RUN yum -y update && \
	yum -y install \
	gcc

WORKDIR /usr/local/src

COPY . ./

RUN make -C linux clean all

ENTRYPOINT ["linux/ccextractor"]
