FROM centos:6.8

MAINTAINER "Sergey Zolotorev" <sergey.zolotorev@dsr-company.com>

RUN yum -y install \
		epel-release \
		gcc && \
	yum -y install \
		yasm && \
	curl https://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2 | tar -jx && \
	pushd ffmpeg && \
		./configure --libdir=/usr/lib64 --prefix=/usr && \
		make install && \
	popd && \
	rm -rf ffmpeg

COPY . /usr/src/ccextractor/

RUN make ENABLE_FFMPEG=yes -C /usr/src/ccextractor/linux clean all install

CMD ["ccextractor"]
